apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: Back_To_Work
    tier: backend
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: NodePort
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 8000
  selector:
    app: Back_To_Work
    tier: backend